version: 0.1-{build}
skip_tags: true
build_script:
- cmd: >-
    appveyor.bat
on_failure:
- 7z a -mx9 -r fail.7z *.exe *.sln *.txt *.log
- appveyor.exe PushArtifact fail.7z
shallow_clone: true
test: off
artifacts:
- path: binary.7z
skip_commits:
  files:
    - 'LICENSE'
    - '*.md'
    - '.gitingore'
    - '.gitattributes'